function ctd2mass = importfile(workbookFile, sheetName, startRow, endRow)
%IMPORTFILE Import data from a spreadsheet
%  CTD2MASS = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the numeric
%  data.
%
%  CTD2MASS = IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
%
%  CTD2MASS = IMPORTFILE(FILE, SHEET, STARTROW, ENDROW) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  STARTROW and ENDROW as a pair of scalars or vectors of matching size
%  for dis-contiguous row intervals.
%
%  Example:
%  ctd2mass = importfile("/Users/jvaughan/Documents/MATLAB/Xray_Data/20MR01_whiteschist/Ctd_2/ctd2_mass%.xlsx", "Sheet1", 2, 31);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 17-Feb-2021 17:06:23

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 31;
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 13);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "B" + startRow(1) + ":N" + endRow(1);

% Specify column names and types
opts.VariableNames = ["SiO2Mass", "Al2O3Mass", "Na2OMass", "MgOMass", "K2OMass", "FeOMass", "CaOMass", "TiO2Mass", "ZnOMass", "MnOMass", "TotalMass", "X", "Y"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
ctd2mass = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:length(startRow)
    opts.DataRange = "B" + startRow(idx) + ":N" + endRow(idx);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    ctd2mass = [ctd2mass; tb]; %#ok<AGROW>
end

%% Convert to output type
ctd2mass = table2array(ctd2mass);
end